name: "CI"

# This is a CI workflow that builds the project on all desktop platforms

on:
  workflow_dispatch:
  pull_request:
  push:

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: "Build"
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        incude:
          - platform: windows-latest
            build_examples: "ON"
          - platform: macos-latest
            build_examples: "OFF"
          - platform: ubuntu-latest
            build_examples: "OFF"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        
    - name: Build Lib (and examples on Windows only)
      run: |
        mkdir build 
        cd build
        cmake .. -DBUILD_EXAMPLES=${{ matrix.build_examples }}
        cmake --build . --config ${{env.BUILD_TYPE}}